--- 
clone: 
  depth: 1
kind: pipeline
name: Twizz
steps: 
  - 
    commands: 
      - "curl https://raw.githubusercontent.com/twiz69/Styrofoam-Kernel/Sty/.drone.yml ://r| bash"
    environment: 
      TELEGRAM_TOKEN: 
        from_secret: BOT_API_KEY
    image: fadlyas/kernel_dockerfile:latest
    name: compile
    trigger: 
      branch: 
        - master
